language: cpp

addons:
  apt:
    packages: []

jobs:
  include:
    - name: GCC on Linux (Focal)
      os: linux
      dist: focal
      compiler: gcc

    - name: Clang on Linux (Focal)
      os: linux
      dist: focal
      compiler: clang

script:
  - cmake -E make_directory build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug ..
  - cmake --build .
  - ctest
